export const usersRawData = [
  {
    fullname: "User One",
    email: "userone@gmail.com",
    roleNo: "MCA01",
    role: "student",
    action: {},
  },
  {
    fullname: "User Two",
    email: "usertwo@gmail.com",
    roleNo: "MCA01",
    role: "student",
    action: {},
  },
  {
    fullname: "User Three",
    email: "userthree@gmail.com",
    roleNo: "MCA01",
    role: "student",
    action: {},
  },
  {
    fullname: "User Four",
    email: "userfour@gmail.com",
    roleNo: "",
    role: "Faculty",
    action: {},
  },
  {
    fullname: "User Five",
    email: "userfive@gmail.com",
    roleNo: "",
    role: "Faculty",
    action: {},
  },
  {
    fullname: "User Six",
    email: "usersix@gmail.com",
    roleNo: "MCA01",
    role: "student",
    action: {},
  },
  {
    fullname: "User Seven",
    email: "userseven@gmail.com",
    roleNo: "MCA01",
    role: "student",
    action: {},
  },
  {
    fullname: "User Eight",
    email: "usereight@gmail.com",
    roleNo: "",
    role: "Manager",
    action: {},
  },
  {
    fullname: "User Nine",
    email: "usernine@gmail.com",
    roleNo: "MCA01",
    role: "student",
    action: {},
  },
  {
    fullname: "User Ten",
    email: "userten@gmail.com",
    roleNo: "MCA01",
    role: "student",
    action: {},
  },
];
